modLoader="javafml"
loaderVersion="[43,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/lazul1ne/apugli/issues"

[[mods]]
modId="toomanyorigins"
version="${version}"
displayName="TooManyOrigins"
#updateJSONURL=""
displayURL="https://github.com/lazul1ne/toomanyorigins"
logoFile="pack.png"
authors="MerchantPug, Lazuline"
description="An addon to Origins loosely inspired by the original mod."

[[dependencies.toomanyorigins]]
modId="forge"
mandatory=true
versionRange="[43.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,1.19.3)"
ordering="NONE"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="origins"
mandatory=true
versionRange="[1.19.2-1.7.1.1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.toomanyorigins]]
modId="apugli"
mandatory=true
versionRange="[2.6.2,)"
ordering="AFTER"
side="BOTH"